package fr.ensisa.hassenforder.chatrooms.server;

public enum OperationStatus {

	NOW_CONNECTED,
	NOW_DISCONNECTED,
	CHANNEL_CREATED,
	SUBSCRIPTION_CHANGED,
	APPROBATION_CHANGED,
	MESSAGE_SENT,

	NOT_CONNECTED,
	ALLREADY_CONNECTED,
	UNKNOWN_USER,
	CHANNEL_EXISTS,
	CHANNEL_CREATION_FAILED,
	UNKNOWN_CHANNEL,
	UNKNOWN_MESSAGE,
	
}
